title:              Pursuit of AI
email:              smartanonymousprof13@example.com
description:        Embark on a journey to success in Artificial Intelligence
author:             SmartAnonymousProf
baseurl:            ""
url:                "https://SmartAnonymousProf.github.io"

# Social Profiles
twitter_username:   
github_username:  SmartAnonymousProf  
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
